export const ROLES = {
  SUPER_ADMIN: "SUPER_ADMIN",
  PLATFORM_ADMIN: "PLATFORM_ADMIN",
  DEPARTMENT_ADMIN: "DEPARTMENT_ADMIN",
  FACULTY: "FACULTY",
  STUDENT: "STUDENT",
  ALUMNI: "ALUMNI",
} as const;

export const PERMISSIONS = {
  DEPARTMENT_CONTENT_MANAGE: "DEPARTMENT_CONTENT_MANAGE",
  DEPARTMENT_GALLERY_MANAGE: "DEPARTMENT_GALLERY_MANAGE",
  DEPARTMENT_ACHIEVEMENT_MANAGE: "DEPARTMENT_ACHIEVEMENT_MANAGE",
  DEPARTMENT_FACULTY_MANAGE: "DEPARTMENT_FACULTY_MANAGE",
  DEPARTMENT_STUDENT_MANAGE: "DEPARTMENT_STUDENT_MANAGE",
  DEPARTMENT_PROGRAM_MANAGE: "DEPARTMENT_PROGRAM_MANAGE",
  DEPARTMENT_SETTINGS_MANAGE: "DEPARTMENT_SETTINGS_MANAGE",
} as const;

export const CONTENT_STATUS = {
  DRAFT: "draft",
  PUBLISHED: "published",
  ARCHIVED: "archived",
  HIDDEN: "hidden",
} as const;

export const VERIFICATION_STATUS = {
  PENDING: "pending",
  APPROVED: "approved",
  REJECTED: "rejected",
  REVOKED: "revoked",
} as const;

export const STORAGE_BUCKETS = {
  AVATARS: "avatars",
  COVERS: "covers",
  GALLERY: "gallery",
  PROFILES: "profiles",
  ACHIEVEMENTS: "achievements",
  CONTENT: "content",
  DEPARTMENTS: "departments",
} as const;
