export const RAVENSHAW_DEPARTMENTS = [
  "Botany",
  "Business Administration",
  "Chemistry",
  "Commerce",
  "Computer Application",
  "Computer Science",
  "Economics",
  "Education",
  "English",
  "Geography",
  "Geology",
  "Hindi",
  "History",
  "Information Technology Management",
  "Journalism and Mass Communication",
  "Mathematics",
  "Odia",
  "Philosophy",
  "Physics",
  "Political Science",
  "Psychology",
  "Sanskrit",
  "Sociology",
  "Statistics",
  "Zoology"
];
