import { z } from "zod";
import { ROLES, PERMISSIONS } from "../constants";

export const roleSchema = z.enum([
  ROLES.SUPER_ADMIN,
  ROLES.PLATFORM_ADMIN,
  ROLES.DEPARTMENT_ADMIN,
  ROLES.FACULTY,
  ROLES.STUDENT,
  ROLES.ALUMNI,
]);

export const permissionSchema = z.enum([
  PERMISSIONS.DEPARTMENT_CONTENT_MANAGE,
  PERMISSIONS.DEPARTMENT_GALLERY_MANAGE,
  PERMISSIONS.DEPARTMENT_ACHIEVEMENT_MANAGE,
  PERMISSIONS.DEPARTMENT_FACULTY_MANAGE,
  PERMISSIONS.DEPARTMENT_STUDENT_MANAGE,
  PERMISSIONS.DEPARTMENT_PROGRAM_MANAGE,
  PERMISSIONS.DEPARTMENT_SETTINGS_MANAGE,
]);
