export const innerPageHeroImages = {
  departments: "/hero/hero-1.webp",
  hostels: "/hero/hero-1.webp",
  organizations: "/hero/hero-1.webp",
  people: "/hero/hero-1.webp",
  community: "/hero/hero-1.webp",
  gallery: "/hero/hero-1.webp",
  events: "/hero/hero-1.webp",
  achievements: "/hero/hero-1.webp",
  news: "/hero/hero-1.webp",
  stories: "/hero/hero-1.webp",
  publications: "/hero/hero-1.webp",
  alumni: "/hero/hero-1.webp",
  support: "/hero/hero-1.webp",
  donations: "/hero/hero-1.webp",
  contact: "/hero/hero-1.webp",
  about: "/hero/hero-1.webp",
  legal: "/hero/hero-1.webp",
  default: "/hero/hero-1.webp",
};
